### ISSUE TITLE
Add info on "How to run deltashape" or other python2/3 programs with conda env"

### ISSUE THREAD

**Issue by dukechem** [Weeks-UNC/small-scripts#1]
### Documentation request... 

( One of the folks here at Duke Chemsitry Dept put instructions below at private wiki at gitlab.oit.duke.edu and perhaps you want to make such a howto available publicly.) --Bill Day

(not a bug/issue) Can you please add info something like "How to run deltashape" or other python2/3 programs with conda env" similar to that below? You might have to fix the one link at top to make sure it actually goes down to the  one-time-only-setup-procedure anchor ;-)

----
---
### How to run deltashape.py (or any other python program) with conda. ###

NOTE: These commands can be used anytime you want to run the program, but *only* after you do the [one-time-only setup procedure ](#one-time-only-setup-procedure) (below).
 
(By the way, examples below shows a ```barb$``` prompt because we are on Barb's macbook. So your prompt will be different, depending on your username, and computer: mac, windows, linux, etc. But commands to use are same on any computer.) 

For any python program we use general commands similar to these (the first 2 may not be needed):
``` 
                               conda init bash
                               bash  --login 
                               conda activate <some-environment>
                               cd  <the folder having files you need>
                               some-program.py
```
In example below we will run ```deltashape.py``` in /Users/Shared folder where we have ```mymap1.tsv mymap2.tsv```, the two tab-separated map text files. HINTS: You may avoid some problems by choosing filenames that are all lower case with no spaces ;-) And you just need to type first part of filename then hit tab key to auto fill-in the rest of the name (or to see your autocompletion choices).
 
NOTE: All commands to use are off to the right, like ``` python --version``` below. You should be able to copy and paste them into the Terminal.
``` command 
barb$                          conda activate py2-deltashape
(py2-deltashape) barb$         python --version
Python 2.7.18 :: Anaconda, Inc.
```
Next use ```cd  ``` to navigate to folder with your 2 map files like so: 
Type ```cd  ``` then in Finder, drag the folder where your files are to terminal.
For example if you drag the "Shared" folder (in /Users/) to the terminal you see:
``` command
(py2-deltashape) barb$         cd   /Users/Shared/
(py2-deltashape) Shared barb$  pwd
/Users/Shared
```
Note: The prompt or ```pwd``` shows name of folder we are in, like ```Shared```...
Whatever folder we are in, we just type ``` deltashape.py``` then any optional arguments you want, if any, (shown in square brackets below, and finally the names of the 2 required map files. Below ```mymap1.tsv  mymap2.tsv``` are the names of the 2 files in /Users/Shared/ folder.

NOTE: Each map file is a 4-column tab-delimited format, as described in README file that comes with deltashape download. I suggest ending map filenames in ```.tsv``` meaning "Tab Separated Values" (in same way that ```.csv```  means the "Comma Separated Values" text-file format. You may be able more easily create and save to filenames ending in ```.tsv``` with excel or other software. For example you can tell macos to use free [Textmate](http://manual.textmate.org/) to open ```.tsv``` files when you double-click on them, and such software will highlight the tabs, and warn you if you have 2 tabs where you should only have 1, etc.

```
(py2-deltashape) Shared barb$               deltashape.py
usage: deltashape.py [--mask5 MASK5] [--mask3 MASK3] [-p PAD] [-z ZCOEFF]
                     [-t ZTHRESH] [-s SSTHRESH] [-f FINDSITE] [-o OUT]
                     [--magrank] [--all] [--pdf] [--noshow] [--noplot]
                     [--dots] [--Zdots] [--SSdots] [--colorfill] [--ymin YMIN]
                     [--ymax YMAX] [--xmin XMIN] [--xmax XMAX] [-h]
                     mapFile1 mapFile2
deltashape.py: error: too few arguments

(py2-deltashape) Shared barb$              deltaSHAPE.py mymap1.tsv mymap2.tsv
```
Double-click the README.txt for info on file-formats, optional arguments.
 
----
----
<h3 id="one-time-only"> one-time-only setup procedure </h3>

You need to do a setup procedure like below just one-time-only. It creates the correct environment that you later activate anytime you need to run your python program. In this example we'll setup  deltashape.py with the procedure for other python programs being much the same. 

* Install free [Anaconda](https://www.anaconda.com/] or miniconda software
  * For macos try ```  brew  install  miniconda``` 
  * For windows try ```choco install  miniconda```

* You may need to download the python program if ``` conda search``` (or a search in Anaconda) does not find it. In this case, we do need to download deltashape from [weekslab.com/software/](https://weekslab.com/software/) Double-clicking the file downloaded should create a folder named something like ```deltaSHAPE_v1.0``` in your Downloads folder, with a README file you can open. Note however we deviate from the README in a few areas: I suggest you create map files whose name end in ```.tsv``` instead of ```.map``` or ```.dat``` (the name does not matter). And wherever possible we'll use ```conda install <whatever>``` instead of other methods like ```pip``` or ```setup.py```.

*  In Terminal, copy and paste the following command:
``` 
conda create --name py2-deltashape python=2.7 
``` 
And you should see something like below...

``` command
$          conda create --name py2-deltashape python=2.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done
``` 
... and more stuff all  ending in ```Proceed ([y]/n)? ``` so press Y then return key.
``` The following packages will be downloaded:
....
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.33.6-py27_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3

Proceed ([y]/n)? 
```
And it will proceed to finish installing everything for that env...
```
certifi-2019.11.28   | 153 KB    | ###################################################################### | 100% 
pip-19.3.1           | 1.7 MB    | ###################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py2-deltashape
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
* Use commands below to activate. Once an env is active, prompt is changed to start with name of current environment, in this case ```(py2-deltashape) ```

``` command
barb$                                               conda init bash
barb$                                               bash --login
barb$                                               conda deactivate
barb$                                               conda activate py2-deltashape
(py2-deltashape) barb$ 
```

* The README.txt tells us to install a few other modules...
```
  In order to run deltaSHAPE.py, you must have Python 2.7 installed, as
  well as two additional modules:
  
  matplotlib, freely available from http://www.matplotlib.org
  NumPy, freely available from http://www.numpy.org
  SciPy, freely available from http://www.scipy.org
```
So just use ```conda install -c anaconda [module-name]``` for each of above modules, and just return(enter) key each time you see ```Proceed ([y]/n)?```

``` command
(py2-deltashape) barb$            conda install -c anaconda matplotlib
Collecting package metadata (current_repodata.json): done
### ... you will see a bunch of info about packages to be installed here ... ###
Proceed ([y]/n)?

(py2-deltashape) barb$             conda install -c anaconda numpy
### ... you will see a bunch of info about packages to be installed here ... ###
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(py2-deltashape) barb$             conda install -c anaconda SciPy
### ... ###
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.2.1                |   py27h1410ff5_0        15.7 MB  anaconda
Downloading and Extracting Packages
scipy-1.2.1          | 15.7 MB   | ###################################################################### | 100% 
Preparing transaction: done
```
* Finally, we'll copy deltashape to a folder in our ```PATH```, and run it with python2.7. We can run from any folder, like ``` /Users/Shared/``` with ```cd```

```command
(py2-deltashape) barb$         cd ~/.conda/envs/py2-deltashape/bin
(py2-deltashape) barb$         cp ~/Downloads/deltaSHAPE_v1.0/deltaSHAPE.py .
```
We are now done with the one-time-only setup, and can now run deltashape.py anytime a few simple steps: activat the env, do a ```cd``` to folder with map files, then ```deltashape.py``` (as shown at top of this webpage).

**Comment by Psirving** [comment]
I like this idea. Thanks for this recommendation. Over time, I'd like to make the software from our lab as accessible as possible through our team's GitHub page, including instructions for an easily reproducible environment. However, I've got a lot on my plate right now. This will have to wait. In the meantime, if there's anything specific you're having trouble with, generally I respond quickly to these GitHub issues. I'm going to close this issue, but this will remain on my to-do list.

**Comment by porteusconf** [comment]
A file named ```environment.yml ``` is attached to this comment, and even tho the issue was closed, I think that file reduces the steps needed to run deltashape to just the very few below. 

The file was created by ``` conda env export > environment.yml``` while in the ```py2-deltashape``` env per steps at [Sharing an environment](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)

So I believe anyone with conda installed could now run deltashape by just the few steps below, instead of all those steps in my original post. 

* Put the environment.yml file in a deltaSHAPE folder along with the readme file (with this info added to the readme). Zip it up and/or otherwise available to end-user like [deltaSHAPE.zip](https://github.com/Weeks-UNC/small-scripts/files/4637150/deltaSHAPE.zip)

* Assuming end-user already has installed Anaconda/minconda3 (as described in original post above),  then in Terminal, they just navigate to folder where ```environment.yml ``` is located (for example deltaSHAPE  in Downloads).

```	
        cd  ~/Downloads/deltaShape
```
* Copy and paste the following command:
``` 
	conda env create -f environment.yml
```

This will create a conda env named py2-deltashape you can use to run deltashape as mentioned in original post. In a nutshell:
```
         conda activate py2-deltashape  
         cp  ~/Downloads/deltaSHAPE.py   $dirname  $(which python))   ### or somewhere  in path
         cd   /path/to/folder/with/mapfiles
	 deltaSHAPE.py  mymap1.tsv  mymap2.tsv
```
With your permission I may create a github project for deltashape with this info. I'm thinking of tweaking it so map files can be (*.csv) comma-separated-value files as well as (*.tsv) tab-separated files.

**Comment by Psirving** [comment]
There's no license included in the deltaSHAPE README, You can contact the author, Matt Smola, to make sure, but I'm pretty sure this is fine. His gmail account is included in the README file. I will likely do something similar in the future, or possibly include a link to your repo on our page. If you do this, please share it with me!

**Comment by Psirving** [comment]
Sorry, I missed it. Right below the author line:

```
Copyright
  ---------

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by Psirving** [comment]
FYI I have added deltaSHAPE to our public repos if you want to fork it and make modifications.
